### ISSUE TITLE
Vue example doesn't work

### ISSUE THREAD

**Issue by shestpa** [muenzpraeger/sfdx-lwc-preact-svelte-vue-example#4]
Good afternoon!
Colleagues, seems like a component using Vue is not working:
![Screenshot 2023-03-28 at 16 22 21](https://user-images.githubusercontent.com/8347217/228221057-0832b008-4437-46c8-aa15-5c9d787d01ab.png)
![Screenshot 2023-03-28 at 16 22 27](https://user-images.githubusercontent.com/8347217/228221046-5f896918-aa6a-4bb0-b6f3-24cb02750c6a.png)

Stack trace:
`TypeError: Cannot read properties of undefined (reading 'id')
    at bn.cleanupDeps (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:6:26975)
    at bn.get (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:6:26686)
    at new bn (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:6:26477)
    at t (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:6:64313)
    at In.$mount (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:6:64460)
    at t._init (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:6:32807)
    at new In (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:6:30137)
    at Array.Go (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:6:69383)
    at Proxy.renderedCallback (eval at <anonymous> (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352)), <anonymous>:1:508)
    at eval (eval at Ty (https://static.lightning.force.com/na212/auraFW/javascript/f-ORwbkOzgxJoD8-NarJXg/aura_prod.js:55:71352), <anonymous>:3:25279)`

What could be the problem here?

**Comment by shestpa** [comment]
A small clarification - local preview works well: 
![Screenshot 2023-03-28 at 16 25 51](https://user-images.githubusercontent.com/8347217/228221559-3553ca09-b45c-478b-8977-13efb66796a7.png)

**Comment by muenzpraeger** [comment]
@shestpa The repo is pretty old, so there may be differences (i. e. Lightning Web Security), which causes this.

**Comment by krishnareddySalesforce** [comment]
LWC1503: Usage of `process` is not allowed (6:3993)            
              LWC1503: Usage of `process.env.VUE_ENV` is not allowed (6:4020)
